import { describe, it, expect } from 'vitest';
import { calculateSpentByBucket } from './calculateCategoryBreakdown';
import type { DistributionCategory, Movement } from '../domain/models/types';

/**
 * FR-012 integration check: does a linked Movement generated by the
 * `create_shared_movement` RPC (User Story 3) flow into the existing budget
 * calculation without any changes to calculateSpentByBucket?
 *
 * Documented, real limitation found while implementing this: the creator's
 * OWN linked movement can be assigned to one of their own buckets (they own
 * that data), but a NON-creator member's linked movement cannot be — the
 * creator has no read access to another member's private
 * DistributionCategory rows (correctly, by RLS), so there is no
 * distribution_category_id to assign on their behalf. That share still
 * counts toward the member's overall income/expense totals (it's an
 * ordinary Movement row), but NOT toward any single bucket's spend until
 * that member categorizes it themselves — which FR-011 currently blocks
 * entirely (linked movements can't be edited at all). Flagged as a known
 * follow-up rather than silently claimed as fully solved.
 */
describe('shared movement -> calculateSpentByBucket integration (FR-012)', () => {
  const baseMovement = {
    id: 'm-ana', type: 'EXPENSE' as const, amount: 5000, date: new Date(),
    is_recurring: false, shared_movement_id: 'sm-1', is_linked: true,
    created_at: new Date(), updated_at: new Date(),
  };

  it('counts the linked movement toward a bucket when the creator assigns their own bucket to their own share', () => {
    const bucket: DistributionCategory = {
      id: 'bucket-1', user_id: 'ana', name: 'Necesidades', percentage: 50,
      is_default: true, is_savings: false, created_at: new Date(), updated_at: new Date(),
    };
    const anaMovement: Movement = { ...baseMovement, user_id: 'ana', distribution_category_id: 'bucket-1' };

    const spent = calculateSpentByBucket([anaMovement], [bucket]);

    expect(spent['bucket-1']).toBe(5000);
  });

  it('documents that a non-creator member\'s linked movement has no bucket and is excluded from any bucket\'s spend', () => {
    const bobBucket: DistributionCategory = {
      id: 'bucket-2', user_id: 'bob', name: 'Necesidades', percentage: 50,
      is_default: true, is_savings: false, created_at: new Date(), updated_at: new Date(),
    };
    const bobMovement: Movement = { ...baseMovement, id: 'm-bob', user_id: 'bob' }; // no distribution_category_id

    const spent = calculateSpentByBucket([bobMovement], [bobBucket]);

    expect(spent['bucket-2']).toBe(0); // known limitation, not a silent bug
  });
});
