import { SharedSpacePermissionMode, UUID } from '../domain/models/types';

/**
 * A Movement generated by a SharedMovement can only ever be touched through
 * that SharedMovement (FR-011) — never directly, regardless of who owns it
 * or the space's permission mode.
 */
export function canEditLinkedMovement(movement: { is_linked?: boolean }): boolean {
  return !movement.is_linked;
}

export interface CanEditSharedMovementParams {
  actingUserId: UUID;
  sharedMovementCreatedBy: UUID;
  permissionMode: SharedSpacePermissionMode;
}

/**
 * Whether a SharedMovement itself may be edited/deleted (FR-015): the
 * creator always can; anyone else only when the space is in "open" mode.
 */
export function canEditSharedMovement(params: CanEditSharedMovementParams): boolean {
  if (params.permissionMode === 'open') return true;
  return params.actingUserId === params.sharedMovementCreatedBy;
}
