import { describe, it, expect } from 'vitest';
import { canEditLinkedMovement, canEditSharedMovement } from './guardMovementEdit';

describe('canEditLinkedMovement', () => {
  it('rejects editing a Movement generated by a SharedMovement (FR-011)', () => {
    expect(canEditLinkedMovement({ is_linked: true })).toBe(false);
  });

  it('allows editing an ordinary, unlinked Movement', () => {
    expect(canEditLinkedMovement({ is_linked: false })).toBe(true);
    expect(canEditLinkedMovement({})).toBe(true);
  });
});

describe('canEditSharedMovement', () => {
  it('allows the creator to edit their own shared movement in strict mode', () => {
    expect(canEditSharedMovement({
      actingUserId: 'ana', sharedMovementCreatedBy: 'ana', permissionMode: 'strict',
    })).toBe(true);
  });

  it('rejects a non-creator editing someone else\'s shared movement in strict mode (FR-015 default)', () => {
    expect(canEditSharedMovement({
      actingUserId: 'bob', sharedMovementCreatedBy: 'ana', permissionMode: 'strict',
    })).toBe(false);
  });

  it('allows a non-creator to edit any shared movement when the space is in open mode (FR-015)', () => {
    expect(canEditSharedMovement({
      actingUserId: 'bob', sharedMovementCreatedBy: 'ana', permissionMode: 'open',
    })).toBe(true);
  });
});
