export type UUID = string;

export interface BaseEntity {
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date;
}

export interface Profile extends BaseEntity {
  id: UUID;
  last_recurrence_eval_month?: string; // YYYY-MM
  notification_hour?: number; // 0-23, local hour for the daily reminder (RF-16)
  push_enabled?: boolean; // browser Notification API opt-in
  inapp_enabled?: boolean; // in-app notification history opt-in
}

export interface IncomeSource extends BaseEntity {
  id: UUID;
  user_id: UUID;
  name: string;
  amount: number; // in cents
}

export interface DistributionCategory extends BaseEntity {
  id: UUID;
  user_id: UUID;
  name: string;
  percentage: number; // 1-100
  is_default: boolean;
  is_savings: boolean; // identifies the "savings" bucket for goal assignment (RF-14), not a name match
}

export interface ExpenseCategory extends BaseEntity {
  id: UUID;
  user_id: UUID;
  distribution_category_id: UUID; // every expense category belongs to exactly one distribution bucket (RF-08)
  name: string;
}

export interface ExpenseSubcategory extends BaseEntity {
  id: UUID;
  category_id: UUID;
  name: string;
}

export interface SavingsGoal extends BaseEntity {
  id: UUID;
  user_id: UUID;
  name: string;
  target_amount: number; // in cents
  deadline?: Date;
}

export interface Movement extends BaseEntity {
  id: UUID;
  user_id: UUID;
  type: 'INCOME' | 'EXPENSE';
  amount: number; // in cents
  date: Date;
  description?: string;
  distribution_category_id?: UUID;
  expense_category_id?: UUID;
  expense_subcategory_id?: UUID;
  income_source_id?: UUID;
  savings_goal_id?: UUID;
  is_recurring: boolean;
  shared_movement_id?: UUID; // present only if generated by a SharedMovement
  is_linked?: boolean; // true blocks direct edit/delete outside that SharedMovement (FR-011)
}

export type NotificationType = 'budget_over_80' | 'goal_completed' | 'daily_reminder' | 'loan_due_soon' | 'shared_movement_added' | 'habit_reminder' | 'streak_at_risk' | 'task_due';

export interface Notification extends BaseEntity {
  id: UUID;
  user_id: UUID;
  type: NotificationType;
  title: string;
  body: string;
  read_at?: Date;
  related_id?: string; // bucket id (budget_over_80), goal id (goal_completed), or debt id (loan_due_soon)
  cycle_key?: string; // 'YYYY-MM' for budget_over_80, 'YYYY-MM-DD' for daily_reminder/loan_due_soon, undefined for goal_completed
}

export type SharedSpacePermissionMode = 'strict' | 'open';
export type SharedSpaceStatus = 'active' | 'archived';

export interface SharedSpace extends BaseEntity {
  id: UUID;
  name: string;
  permission_mode: SharedSpacePermissionMode;
  status: SharedSpaceStatus;
  created_by: UUID; // informational only — no admin role attached to this
}

export interface Membership extends BaseEntity {
  id: UUID;
  shared_space_id: UUID;
  user_id: UUID;
  joined_at: Date;
  left_at?: Date; // presence means the member left; never reactivated
}

export type SharedMovementType = 'income' | 'expense';
export type SharedMovementSplitMode = 'percentage' | 'fixed_amount';

export interface SharedMovementSplit {
  user_id: UUID;
  share_cents: number;
}

export interface LinkedMovementRef {
  user_id: UUID;
  movement_id: UUID;
}

export interface SharedMovement extends BaseEntity {
  id: UUID;
  shared_space_id: UUID;
  created_by: UUID; // the member who fronted the money for this movement
  type: SharedMovementType;
  total_amount_cents: number;
  split_mode: SharedMovementSplitMode;
  splits: SharedMovementSplit[]; // what each member owes for this movement
  linked_movement_ids: LinkedMovementRef[]; // one personal Movement per member
  date: Date;
}

export interface SharedInvite extends BaseEntity {
  id: UUID;
  shared_space_id: UUID;
  code: string;
  created_by: UUID;
  expires_at: Date;
  redeemed_by?: UUID;
  redeemed_at?: Date;
}

export type HabitScheduleMode = 'fixed_days' | 'frequency';
export type DayOfWeek = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';

export interface Habit extends BaseEntity {
  id: UUID;
  user_id: UUID;
  name: string;
  schedule_mode: HabitScheduleMode;
  fixed_days?: DayOfWeek[]; // required if schedule_mode = 'fixed_days', at least one
  frequency_target?: number; // required if schedule_mode = 'frequency', >= 1
}

export interface HabitCompletion extends BaseEntity {
  id: UUID;
  habit_id: UUID;
  date: Date;
  token_used: boolean; // true if a streak-protection token covered this day instead of a real completion
}

export type GoalKind = 'numeric' | 'checklist';
export type GoalStatus = 'active' | 'completed';

export interface GoalMilestone {
  id: UUID;
  label: string;
  done: boolean;
}

export interface Goal extends BaseEntity {
  id: UUID;
  user_id: UUID;
  name: string;
  kind: GoalKind;
  target_value?: number; // required if kind = 'numeric'
  current_value?: number; // only meaningful if kind = 'numeric'
  milestones?: GoalMilestone[]; // required if kind = 'checklist'
  status: GoalStatus;
  completed_at?: Date;
}

export type TaskStatus = 'pending' | 'done';

export interface Task extends BaseEntity {
  id: UUID;
  user_id: UUID;
  title: string;
  due_date: Date;
  status: TaskStatus;
  done_at?: Date;
}

export type DebtDirection = 'lent' | 'borrowed';
export type DebtOrigin = 'manual' | 'shared_expense';

export interface Debt extends BaseEntity {
  id: UUID;
  user_id: UUID;
  counterparty_name: string;
  direction: DebtDirection;
  origin: DebtOrigin;
  shared_movement_id?: UUID; // set once origin === 'shared_expense' (family-space feature, not yet implemented)
  amount: number; // in cents
  settled_amount: number; // in cents; accumulates partial repayments, never exceeds `amount`
  due_date?: Date;
  interest_rate?: number; // informational only (spec.md Assumptions) — never recalculated
}

// InstallmentLoan/InstallmentPayment (spec 002, US3) — a separate entity from
// Debt on purpose (research.md #3): bank/caja loans with a lender-defined
// installment schedule. The app never computes an amortization table — every
// number (amount, installment_count, installment_amount) comes verbatim from
// the user, who copies it from their lender (FR-011, FR-012).
export type InstallmentLoanStatus = 'active' | 'settled';
export type InstallmentPaymentKind = 'installment' | 'principal';
export type InstallmentAdjustmentType = 'reduce_term' | 'reduce_installment_amount';

export interface InstallmentLoan extends BaseEntity {
  id: UUID;
  user_id: UUID;
  lender_name: string;
  amount: number; // in cents, total originally borrowed (FR-011)
  installment_count: number; // originally pactado, never changes on its own
  remaining_installments: number; // 0 <= remaining_installments <= installment_count
  installment_amount: number; // in cents, current — can change via a principal payment (FR-016/FR-017)
  interest_rate?: number; // optional, purely informational, never used to calculate anything (FR-013)
  status: InstallmentLoanStatus; // derived: 'settled' once remaining_installments = 0 (FR-025), never reverts
}

// Append-only payment log (FR-026) — analogous to HabitCompletion. Recording
// one is bookkeeping only (Principio X, FR-027): it NEVER creates, updates,
// or references a Movement, same guarantee applyDebtSettlement already gives
// for Debt.
export interface InstallmentPayment extends BaseEntity {
  id: UUID;
  installment_loan_id: UUID;
  kind: InstallmentPaymentKind;
  amount: number; // in cents
  date: Date;
  adjustment_type?: InstallmentAdjustmentType; // only when kind = 'principal' (FR-016)
  resulting_value?: number; // the value the user typed in themselves — never calculated (FR-017); only when kind = 'principal'
}
