-- Empty baseline stub: restrict_finances_to_admin
-- Foreign migration owned by another app on the shared mvp-lab ledger
-- (mvp-lab-infra/OPERATIONS.md §4). No-op here, never applied/owned by ez-life.
