-- Empty baseline stub: ez_finance_goal_progress_started_at
-- Foreign migration owned by another app on the shared mvp-lab ledger
-- (mvp-lab-infra/OPERATIONS.md §4). No-op here, never applied/owned by ez-life.
