-- Empty baseline stub: enroll_via_rpc_remove_auth_trigger
-- Foreign migration owned by another app on the shared mvp-lab ledger
-- (mvp-lab-infra/OPERATIONS.md §4). No-op here, never applied/owned by ez-life.
